add an atomic counting semaphore implementation (!) and use it to ensure a consistent archive for parallel builds

diff --git a/bin/build-image-set b/bin/build-image-set
--- a/bin/build-image-set
+++ b/bin/build-image-set
@@ -10,6 +10,13 @@ if ! lockfile -l 7200 -r 0 "$CDIMAGE_ROOT/etc/.lock-build-image-set"; then
 fi
 trap "rm -f $CDIMAGE_ROOT/etc/.lock-build-image-set" EXIT HUP INT QUIT TERM
 
+SEM="$CDIMAGE_ROOT/etc/.sem-build-image-set"
+# Set up a counting semaphore for parallel builds.
+if ! SEM_STATE="$(semaphore test-increment "$SEM")"; then
+	# semaphore failed, something went badly wrong
+	exit 1
+fi
+
 IMAGE_TYPE="${1:-daily}"
 DATE="$(next-build-date "$IMAGE_TYPE")"
 
@@ -28,15 +35,43 @@ if [ -z "$DEBUG" ]; then
 fi
 
 if [ -z "$CDIMAGE_NOSYNC" ]; then
-	echo "===== Syncing $CAPPROJECT mirror ====="
-	date
-	anonftpsync
-	ARCHES_COLONS="$(echo "$ARCHES" | tr ' ' ':')"
-	case :$ARCHES_COLONS: in
-		*:hppa:*|*:ia64:*|*:sparc:*)
-			ANONFTPSYNC_CONF="$CDIMAGE_ROOT/etc/anonftpsync.ports" anonftpsync
-			;;
-	esac
+	SYNC_LOCK="$CDIMAGE_ROOT/etc/.lock-archive-sync"
+	if [ "$SEM_STATE" = 0 ]; then
+		echo "===== Syncing $CAPPROJECT mirror ====="
+		date
+		# Acquire lock to allow parallel builds to ensure a
+		# consistent archive.
+		if ! lockfile -r 4 "$SYNC_LOCK"; then
+			echo "Couldn't acquire archive sync lock!" >&2
+			exit 1
+		fi
+		# A trap is already in place, so ensure lock removal by hand.
+		# TODO: very ugly - refactor?
+		set +e
+		CODE=0
+		anonftpsync || CODE="$?"
+		if [ "$CODE" ]; then
+			rm -f "$SYNC_LOCK"
+			exit "$CODE"
+		fi
+		ARCHES_COLONS="$(echo "$ARCHES" | tr ' ' ':')"
+		case :$ARCHES_COLONS: in
+			*:hppa:*|*:ia64:*|*:sparc:*)
+				ANONFTPSYNC_CONF="$CDIMAGE_ROOT/etc/anonftpsync.ports" anonftpsync || CODE="$?"
+				if [ "$CODE" ]; then
+					rm -f "$SYNC_LOCK"
+					exit "$CODE"
+				fi
+				;;
+		esac
+	else
+		echo "===== Parallel build; waiting for $CAPPROJECT mirror to sync ====="
+		if ! lockfile -8 -r 450 "$SYNC_LOCK"; then
+			echo "Timed out waiting for archive sync lock!" >&2
+			exit 1
+		fi
+		rm -f "$SYNC_LOCK"
+	fi
 fi
 
 echo "===== Updating archive of local packages ====="
@@ -103,4 +138,5 @@ if [ -z "$DEBUG" ]; then
 fi
 
 echo "===== Finished ====="
+semaphore decrement-test "$SEM"
 date
