Exit if SEEDS is empty

diff --git a/bin/make-master-task b/bin/make-master-task
--- a/bin/make-master-task
+++ b/bin/make-master-task
@@ -29,6 +29,11 @@ else
 	fi
 fi
 
+if [ -z "$SEEDS" ]; then
+       echo 'Error! SEEDS is empty' >&2
+       exit 1
+fi
+
 for seed in $SEEDS; do
 	# https://blueprints.launchpad.net/ubuntu/+spec/edubuntu-on-two-cds
 	if [ "$CDIMAGE_DVD" != 1 ] && [ "$CDIMAGE_ADDON" != 1 ] && \
